Memory leak fix
openjdk/lanai pull request #182
Opened 2021-02-11 13:03 UTC by prsadhuk

Memory leak fix for couple of strings.

2021-02-11 13:24 UTC, kevinrushforth commented
@prsadhuk you forgot the bug ID in the title of this PR (and thus the commit message)

2021-02-11 17:04 UTC, kevinrushforth requested changes

2021-02-11 17:04 UTC, kevinrushforth commented on src/java.desktop/macosx/native/libawt_lwawt/java2d/metal/MTLGraphicsConfig.m
> +    NSString *str = JNU_GetStringPlatformChars(env, shadersLibName, 0);
This should be of type `char *` not `NSString *`

2021-02-11 17:04 UTC, kevinrushforth commented on src/java.desktop/macosx/native/libawt_lwawt/java2d/metal/MTLGraphicsConfig.m
> +    NSString *str = JNU_GetStringPlatformChars(env, mtlShadersLib, 0);
`char *`

2021-02-11 17:14 UTC, kevinrushforth commented
It runs fine for me on dual screens. I verified that it is hitting the call to `JNU_ReleaseStringPlatformChars`. The only issue is the type of `str`, which should be `char *` (or maybe `const char *`) as noted above.

2021-02-11 17:24 UTC, prsadhuk commented
SwingSet2, J2DDemo works fine with this change.

2021-02-11 17:32 UTC, kevinrushforth approved these changes

2021-02-12 04:47 UTC, aghaisas commented
I tested J2DDemo and SwingSet2 with graphics card switch from integrated to discreet and other way round. No regression is observed.

2021-02-12 04:47 UTC, aghaisas approved these changes

2021-02-12 04:56 UTC, prsadhuk commented
/integrate

2021-02-12 04:57 UTC, closed without merging